* A Job You Did Quickly

Describe a piece of work you did quickly. 

** You should say: 
*** TODO what work it was
*** TODO why you did it quickly
*** TODO how easy or difficult it was 
*** TODO and explain what the result was. *


* Part 3

What are some examples of work that needs to be done quickly?

(Similar to above) What kinds of jobs need to be done quickly?

What machines or equipment help people work faster?

Do you think computers help people to work faster?

Do you like working to a deadline?

Why do you think some people are more efficient than other people when
they do a task?

Can you suggest any methods (or ways) that a person could use to become
more efficient?

What are some examples of occasions when it's important to be on time?

Do you think time management is important?

Do you think it's necessary for people to manage their time well?

Do you have any suggestions (or ideas) on how people can better manage
their time?

Do you think parents should try to teach their children about time
management? (If yes, how?)

What do you think are the advantages and disadvantages of using a
timetable? 

Do you like drawing up plans? (= making detailed plans)

Do you think people will place more emphasis, or less emphasis on
punctuality in the future? 

How do you think ideas about punctuality might change in the next 20 or
30 years? 

For what situations is being on time very important? (Why important?) 

For what situations is it not so important to be on time? (Why not so
important?) 

What are some of the common excuses/reasons that people give when they
are late?

Some of these excuses might not be true. Do you think it is good to be
dishonest like that? 

Are people in China usually punctual (= on time) when they have to be
somewhere at a certain time?  

What do people in China think of people who are late?

(Similar to above) Do you (or, do people in China) think punctuality is
important? (Why?/Why not?) 

Do you think modern technology gives us more time, or less? 

Did people in the past lead a faster-paced life than today, or a
slower-paced life? (How?/Why?) 

Do you think the current working hours of most people are reasonable?

