* An Educational Trip 

** Describe an educational visit that you went on when you were in school.

You should say: 

*** TODO who went with you 

*** TODO where you went 

*** TODO what you did there        

*** TODO and explain what you learned on this trip. 


* Specific Questions

Do schools in China ever organize educational trips for students, for
example, a visit to a museum? 

Do you think school excursions (educational trips) are important (or,
useful)? 

Do you think children really do (or can) learn something from an
educational trip? (How?) 

What are some suitable places for school students to go for an
educational visit? FQ 

In general, what attributes are necessary for an ideal school excursion?


Do you think there is any difference between the places boys would
prefer to visit and the places where girls would prefer to visit? 

What do you think are the benefits of taking children to visit places
where they can learn something? FQ

What role do you think the teacher should play on these school
excursions? FQ 

In general, do you think children learn better inside the classroom or
outside the classroom? FQ 

What are some examples of places where parents could take their children
for an 'educational visit'? 

Do you think it's important for people to get an education? (Why?) 

Do you think that (nowadays) everyone needs some form of training in
order to work? 

Which do you think is better, studying at school or studying at home? 

Do you think children should start school at an earlier age than they do
now? 

Can you think of any other ways for children to learn, besides classroom
instruction? FQ 

Can you think of any outdoor activities in which children can learn
something? 

What can they learn from these activities? 

How has education in China changed in the last few decades? 

Do you think education should be free? 

Do you think schools are really necessary for getting an education? 

How do you think schools will change in the future?  

Do you think more people will study at home in the future? FQ 

Why is it necessary for school students to do homework if they attend
school during the day? 

At home, how do you think parents can help their children learn? FQ 

What do you suggest a parent do if he or she doesn't understand what
their child is studying but still wants to help their child? 

Do you think children can get an education at home, instead of going to
school? FQ 

What is the value of children learning from professional teachers? 

How do you think a student's learning would be affected if the student
did not like his or her teacher? 

Do you think children in poverty stricken areas (i.e., with poor school
facilities or none at all) could benefit from studying at home?  

Do you think modern technology could help these children study at home?
(Hint: internet & television) 

Do you think it's necessary for adults do any any study? 

In the future, do you think adults studying at home will be very common?
FQ 

For adults, what are (or, what would be) the advantages from studying at
home? FQ 

Do you think adults should (ever) continue studying after they start
working? 

Do you think it's good for a company (or any work unit) to provide
training for people? 

Which do you think is better, for a company to provide training or to
directly give employees money (so that they can choose their own
training location and method)? 

Please compare the pros and cons of studying overseas with the pros and
cons of studying in China. 

