* Describe an electrical (or electronic) machine or device you would like to buy.             

** You should say:

*** TODO what special features you would like it to have

*** TODO where (or how) you got to know about it

*** TODO how you would use this thing 

*** TODO and explain why you would like to buy it.


** Part 3 Questions

Do you think there are any shortcomings or dangers to using electrical
equipment in the home? 

What happens when there is a blackout? (= How do people manage when
there is a blackout?) 

What are some examples of electronic or electrical equipment that are
used for communication? 

What are some examples of electronic or electrical equipment that are
used for entertainment?  

What are some advantages and disadvantages of using electrical
equipment? 

Do you think we can now live without electrical appliances? 

What kinds of electrical or electronic appliances do you think we will
have in the future? ( = How do you think electrical & electronic
appliances will develop in the future?) 

What are some of the different forms of electronic communication that
people use in offices today and how are they useful? 

What are the advantages and disadvantages of using new technology in the
workplace? 

Do you think that advancements in office technology will result in fewer
people or more people working in offices in the future?  

What are the effects on people of modern technology such as television
and computers?  

Do you think computers will ever be intelligent enough to replace human
brain power? 

Do you think robots will replace humans for some types of work? 

How do you think modern technology will change the way people work in
the future?  

Can you think of examples of high-tech equipment equipment that people
have in their homes today? 

How are electronic devices today different to those in the past? 

What do you think are the advantages/disadvantages that result from
using these modern devices?  

In what ways have recent changes in technology resulted in changes to
society? 

Do you think the internet is causing (has caused) any social change? 

If a person is not keeping up with changes in technology, how do you
think they feel? 

What do you think will be the future development (and future usage) of
electronic (and electrical) devices? 

What electrical appliances are generally used in homes in China? 

Do you think there are any shortcomings from using electrical household
appliances? 

What are some examples of high-tech equipment that is used in some
classrooms today? 

How has modern science and technology changed the way people work in the
past generation (20 to 30 years)? 

Do you think all of these changes have been changes for the better? 

