
* Describe a special gift that you gave to someone.

** You should say:
*** TODO what the gift was
*** TODO who the gift was for (= who you gave it to)
*** TODO when and where you bought it
*** TODO and explain why it was special


** Specific questions 

  Is gift-giving very important in China?

  On what occasions do people in China give gifts?

  In general, what kinds of gifts do people in China give each other? See
  Note

  Is it very expensive to buy gifts for people in China?

  Do people give you gifts very often?

  Who gives you these gifts, and why?

  Which do you think is better, to give or to receive a gift?

  Do you think gift-giving is good for the economy? 

  What sorts of presents do adults usually give to children? 

  Do children usually give more gifts to adults than adults give to
  children? 

  Do you think it's a waste of money for governments to give gifts to the
  governments of other countries? 

  What would you suggest are some suitable gifts for countries to give
  each other? 

  Do you think it is a good idea for developing countries to accept gifts
  from more wealthy, developed countries? 

  Are these gifts between countries simply displays of friendship or do
  you think the country that gives the gift has other reasons for giving? 

  Do you think gift-giving among people who are doing business together is
  a good idea? 

  What are the reasons why business people give each other gifts? 

  What's the difference between giving a gift out of genuine friendship
  and giving a gift with some commercial goal in mind? 

  In China, when (on what occasions) do people give gifts to others? FQ 

  What sorts of things do they give? 

  Do people today still give the same kinds of gifts that people used to
  give, many years ago? 

  Why do people like to receive gifts? 

  What are some of the possible different reasons why give gifts to other
  people? FQ 

  Do you think it's suitable to give money as a gift? 

  Why do some people not like giving gifts? FQ 

  Do you think something that you made yourself is suitable as a gift?
  FQx2 

  Which do you think is better, to give something you made yourself or to
  give something you bought? (Answer & compare) FQx2 

  Why do some people prefer to buy a gift rather than make a gift
  themselves? 

  Compare giving a gift with receiving a gift. What are the differences
  between the two? 

  Some people don't like receiving gifts. Why do you think they feel that
  way? 
  
  What do you think makes people happier, to receive a gift to to give a
  gift? (Why?) FQ 

  Is it true that the more a person gives you gifts, the more it shows
  that this person likes you? 

  Do you think that expensive gifts are (always) a sign of true
  friendship?  FQ 

  What is the difference between a "precious" (or, "valued") gift and a
  "valuable" gift? * 

  What kinds of things do people in China give as wedding gifts? 

  Do you think people today are more willing to help others than they used
  to be?  FQx2 

  Do you think that people of different ages need different forms of help?

  What should be done to help people find suitable jobs? 

  In schools today in China, are children taught the importance of
  consideration for others? 

  Do young people in China help old people (or, older people) very much?
  FQ 

  Why do you think young people should help old people? 

  How can young people help the elderly? FQ

  Are people today willing to do volunteer work? 

  Do you know how charities work? (= how they are operated) 

  Can you suggest any ways that charities could encourage people to help
  others more? (I.e., to do charitable work or donate money to charity.) 

  Do you think we should give rewards to people who help others?  

  Do you think we should reward a child when he or she does something
  good? 

  What are some suitable ways to reward a child for doing something well,
  such as doing well at school? 

  Do you think that children should always be offered an incentive (a
  reward of some kind) when parents ask their children to do something?  

  (Similar to above) Do you think it's always a good idea to reward
  children? FQ 

  What do you think is the best way to reward people for doing a good job
  at work? 

  Do you know the difference between an 'award' and a 'reward'? * 

  What are some examples of international awards, for example, Olympic
  medals? 

  Do you think these awards are good (or, are useful)? 

  Besides special occasions such as birthdays and festivals, what are some
  other reasons why people give presents to others? 

  Compare self-made (homemade) gifts and gifts that you can buy in a shop.


  Which of these do you think is better? (Why?) 

  Is it difficult to choose presents for people? ( = How do people choose
  gifts?) 

  Do advertisements influence people's choices when they are buying
  gifts?  FQ 

  What would be a suitable gift when saying goodbye to someone after a
  visit? 

  Why do you think some people give an excessive number of gifts to other
  people? 

  What are the personal qualities of a person who is a willing and
  enthusiastic gift-giver? 

  Who (do you think) gets more pleasure, the gift giver or the gift
  receiver? (Why?) FQ 

  On what occasions do people give gifts to others? FQ 

  Do you think people in China should give presents on western festivals
  such as Christmas? 

  Are there any specials gifts that children receive at these special
  times? 

  Besides children, do other people get gifts at these times? 

  Do you think children enjoy receiving presents more than adults do? 

  Compare the differences (and similarities) between gifts for children
  and gifts for adults. 

  What kinds of gifts do children in China usually get? FQ 

  What benefits do children get from these gifts? 

  What factors do (should) people consider when choosing gifts to give to
  (young) children? FQ 

  Do you think toys have any educational value? FQ 

  Is it important to give 'educational toys' to children? FQ 

  Do you think gifts for children that are bought in shops are always
  better than homemade gifts? 

  Do you think adults should choose what gifts to give to children or
  should children be allowed to choose the gifts they are to receive? 

