* Describe an intelligent person you know.

** You should say: 

*** TODO who this person is 

*** TODO when and where you (first) met them (him or her)

*** TODO what kind of person he or she is 

*** TODO and explain why you think this person is intelligent.


* Part 3

Do you think there are more highly intelligent children nowadays,
compared to the past?  (Why?/Why not?)

Do you think it's best for these highly intelligent children to go to
normal schools or do you think they should go to special schools? FQ

How do you think poor students (i.e., students who are not very good at
studying) should be educated?

Do you think poor students could benefit by being educated with the good
students?

And do you think there are any benefits for the good students if all the
students are educated together?

How do you think schools could be improved?

How do you think school education will develop in the future?

What do you think of the idea of replacing teachers in schools with
equipment that has artificial intelligence, such as computers?

What would be the good and bad points if teachers in schools were
replaced by equipment that has artificial intelligence, such as
computers?

Do you think play can help children develop their intelligence? (If yes,
how? If no, why not?)

What sorts of games or play activities do you think most help children
to develop their intelligence?

Which do you think is better (for the development of a child's
intelligence), children playing alone or playing with other children? 

In what ways do you think children can benefit by playing with others
(or, other children)?

