* Describe cafe or restaurant that you know.

** You should say:

*** TODO where it is

*** TODO how often you go there

*** TODO what kind of food they serve there (or, what service they provide)

*** TODO who you usually go there with

*** TODO and explain why you like to eat at this place.


* Part 3

Why do people like to go to restaurants to eat?

Do most restaurants in your country serve traditional food or fast food?

Which do you think is better, big restaurants or small ones?

Would you agree that the more expensive the restaurant, the better the
food?

Do you think there is any connection between food and health? 

What kinds of food are most popular in China? 

Do you think the most delicious food is also the most nutritious? 

Do you think that the most popular food is also the most nutritious
food? 

Is Chinese food very nutritious? 

What  foods are most nutritious and what food are not very nutritious?
FQ 

Do you think that people should eat more healthy food? 

Are there many vegetarians in China? 

Why do you think they don't eat meat? * 

In China, have people's eating habits changed much in the past few
years? 

Besides Chinese food, what other kinds of food do you know about? 

Is Western food very popular in China? 

Why do you think food such as pizza is popular? 

Why do children like Western style fast food? 

Do you think advertising has an effect on what foods people eat? FQ 

Do you think that junk food (or advertising it) should be banned?  FQx2


Who should be responsible for educating the public about correct
nutrition - schools, the government or parents? 

What measures should be taken to increase public awareness of proper
nutrition?  FQ 

How has technology changed the food production process? 

Do you think the government should be concerned with food production and
the sale of food? 

Are there many restaurants near your home/school/university/work?  FQ 

What (different) types of restaurants are there in your hometown? FQ 

What kinds of eating places are there at your school/university? 

Does Chinese families often go to a restaurant to eat? 

What are the most popular kinds of restaurant in China today? 

How have restaurants in China changed in the last few (e.g. 20) years? 

What are some of the factors that make a restaurant a good one? FQx2 

(Similar to above) What makes a restaurant a famous one (or a popular
one)? FQ 

(Similar to above) If you had your own cafe, how would you run it? 

Is foreign food (international food) very popular in China? 

Why do you think some people like the food from a particular country? 

Does the food in the restaurant you just talked about (in Part 2) taste
different to Western food? (Compare the two) FQ 

How is restaurant food different to home cooking? 

Do you think multi-national restaurant companies such as KFC are
changing the food culture of China? 

What personal qualities (and skills) are necessary for working in a
restaurant? 

Do you think the spread of such restaurants is a good thing? 

In China, what is the social significance of eating out with others?
(i.e., eating in restaurants with others)  

In Chinese culture, what are some examples of important occasions when
people eat together in restaurants?  

What are some different reasons why people (not family members) eat
together in a restaurant? 

Is it important in Chinese culture to eat (out) with other people?  FQ 

There is a lot of leftover food in restaurants. What do you think is the
best way to dispose of this food? 

Do people in China often go to coffee shops? 

